### ISSUE TITLE
BlazorBFF works w/Azure AD B2C, but get error when add SignUpSignInPolicyId

### ISSUE THREAD

**Issue by vsdotnetguy** [damienbod/AzureADAuthRazorUiServiceApiCertificate#18]
Hi Damien,

Thanks so much for this excellent example code.  I've been able to get it to work pretty much as-is, however, it is with AAD B2C instead of AAD.  Everything works great until I create a User Flow then add the SignUpSignInPolicyId key to the settings (which effectively eliminates the need for TenantId).  Do I need to add an Authority setting here?  Do we have to introduce MSAL in some way?

The error I'm getting is:
**An unhandled exception occurred while processing the request.
IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)**

Below shows your appSettings.json with the AzureAdB2C name and SignUpSignInPolicyId key (of course I'm using other guids in my code)
`{
  "AzureAdB2C": {
    "Instance": "https://login.microsoftonline.com",
    "Domain": "damienbodhotmail.onmicrosoft.com",
    "TenantId": "7ff95b15-dc21-4ba6-bc92-824856578fc1",
    "ClientId": "46d2f651-813a-4b5c-8a43-63abcb4f692c",
    "CallbackPath": "/signin-oidc",
    "SignedOutCallbackPath ": "/signout-callback-oidc",
    //"ClientSecret": "add secret to the user secrets"
    "SignUpSignInPolicyId": "UserFlow1"
  },
  "UserApiOne": {
    "ScopeForAccessToken": "api://b2a09168-54e2-4bc4-af92-a710a64ef1fa/access_as_user User.ReadBasic.All user.read",
    "ApiBaseAddress": "https://localhost:44395"
  }`

Here is the code to parse the settings and conf auth:
`            services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAdB2C")
                .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                 .AddMicrosoftGraph("https://graph.microsoft.com/beta",
                    "User.ReadBasic.All user.read")
                .AddInMemoryTokenCaches();`

Your help to get beyond this error would be greatly appreciated.

Thanks in advance...Bob Baldwin
aka VSDotNetGuy

**Comment by damienbod** [comment]
Hi Bob

Thanks! Azure B2C does not support the OBO flow. To access downstream APIs in Azure B2C, you need to use the CC flow. This configuration uses the OBO, so you would have to remove the downstream APIs and replace this with a CC client.

pinging @cmatskas just the verify this

Greetings Damien

**Comment by vsdotnetguy** [comment]
Hi again Damien,

Just to confirm as I'm not a strong oauth or openid connect dev. By CC I assume you mean Client Credentials and by OBO you mean On Behalf Of.

I believe I have this working as the Direct and Graph API seems to be working with ADB2C plus I created a custom user flow with claimsexchange via az function to pass approle user assignments into the auth pipeline so blazor client and server knows about RBAC based roles and Authorize attributes work as desired

Thanks again for the help.

**Comment by vsdotnetguy** [comment]
Also it seems OBO is now supported for ADB2C based on https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-developer-notes#oauth-20-application-authorization-flows

**Comment by vsdotnetguy** [comment]
Ok, upon further investigation, I see that OBO is not directly supported but can be used as long as client credential is used for downstream API like MS Graph

**Comment by damienbod** [comment]
I add extra claims like in this example

https://damienbod.com/2021/09/06/using-azure-security-groups-in-asp-net-core-with-an-azure-b2c-identity-provider/

public class GraphApiClaimsTransformation : IClaimsTransformation

Greetings Damien

**Comment by vsdotnetguy** [comment]
Thanks Damien,

We now have your BFF cookie based approach using Microsoft.Web.Identity working nicely in an AD B2C environment.  It uses CC to access MS Graph versus OBO.

I do have another question.  I noticed your code utilizes the ConfigureWait(false) syntax.  One of my associates, believes this is not needed within ASP.Net Core.  Can you explain your reasoning for it and also why it is no longer in the template code you just recently created at https://github.com/damienbod/Blazor.BFF.AzureAD.Template on Nov 29th?

Thanks again for you excellent posts.

**Comment by damienbod** [comment]
Hi @vsdotnetguy thanks

yes ConfigureWait(false) is not needed within an ASP.Net Core context and should be removed. Will fix this.

Greetings Damien

**Comment by vsdotnetguy** [comment]
Understood, thx

**Comment by damienbod** [comment]
Created a Blazor template for this

https://github.com/damienbod/Blazor.BFF.AzureB2C.Template

maybe you could review, test, improve?

Greetings Damien
